config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :staffs do
    resources :votes, only: [:new, :create, :show]
  end
  resources :voted_staffs, except: :update
  get '/votes', to: 'votes#index'
  get '/admin', to: 'pages#admin'
  delete '/admin/votes', to:'pages#destroy', as: :admin_votes
  get '/admin/stop_vote', to: 'pages#stop_vote'

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/staff.rb
class Staff < ApplicationRecord
  validates :email, uniqueness: true, presence: true, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :staff
  belongs_to :voted_staff
end

app/models/voted_staff.rb
class VotedStaff < ApplicationRecord
  has_many :votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @staff = Staff.new
  end

  def admin
    @voted_staff = VotedStaff.new
    @voted_staffs = VotedStaff.all
  end

  def stop_vote
    Vote.new ? false : true
    redirect_to admin_path
  end

  def destroy
    @votes = Vote.all
    @votes.each(&:destroy)
    redirect_to admin_path
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  def index
    @staffs = Staff.all
  end

  def create
    @staff = Staff.new(staff_params)
    @votes = Vote.all
    if @staff.save
      redirect_to staff_path(@staff)
    else
      render 'pages/home'
    end
  end

  def new
    @staff = Staff.new
  end

  def edit
  end

  def show
    @vote = Vote.new
    @voted_staffs = VotedStaff.all
  end

  def update
    if @staff.update(staff_params)
      redirect_to staff_path(@staff)
    else
      render :edit
    end
  end

  def destroy
    @staff.destroy
    redirect_to staffs_path
  end

  private

  def set_staff
    @staff = Staff.find(params[:id])
  end

  def staff_params
    params.require(:staff).permit(:name, :email, :admin)
  end
end

app/controllers/voted_staffs_controller.rb
class VotedStaffsController < ApplicationController
  before_action :set_voted_staff, only: [:show, :edit, :destroy]

  def index
    @voted_staffs = VotedStaff.all
  end

  def new
    @voted_staff = VotedStaff.new
  end

  def create
    @voted_staff = VotedStaff.new(voted_staff_params)
    if @voted_staff.save
      redirect_to voted_staffs_path
    else
      render 'pages/home'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @voted_staff.update(voted_staff_params)
      redirect_to voted_staffs_path
    else
      render :edit
    end
  end

  def destroy
    @voted_staff.destroy
    redirect_to voted_staffs_path
  end

  private

  def set_staff
    @voted_staff = VotedStaff.find(params[:id])
  end

  def voted_staff_params
    params.require(:voted_staff).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :destroy]
  before_action :set_staff, only: [:new, :create, :show]

  def index
    @votes = Vote.all
    @voted_staff = VotedStaff.find_by_id(params[:voted_staff_id])
  end

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.staff = @staff
    if @vote.save!
      redirect_to votes_path, notice: 'You just voted successully!'
    else
      render :new
    end
  end

  def show
    @vote.staff = @staff
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end

  def set_staff
    @staff = Staff.find_by_id(params[:staff_id])
  end

  def vote_params
    params.require(:vote).permit(:staff_id, :voted_staff_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/voted_staffs_helper.rb
module VotedStaffsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NittygrittyStaff</title>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/jpg" href="<%= image_url('favicon.png') %>" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Oswald:300,400,700">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="navbar">
      <%= render "shared/navbar" %>
    </div>
    <div class="content">
      <%= yield %>
    </div>

  </body>
  <footer>
    <%= render "shared/footer" %>
  </footer>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
</html>

app/views/pages/admin.html.erb
<div class="container">
<!-- • add members of staff to the poll -->
  <%= simple_form_for(@voted_staff) do |f| %>
    <div class="form-inputs">
      <%= f.input :name, placeholder: 'STAFF NAME', label: false  %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, 'ADD STAFF TO POLL', class: "btn btn-info" %>
    </div>
  <% end %>
  <!-- • remove members of staff from the poll -->
  <hr>
    <%= simple_form_for(@voted_staff, :method => :destroy) do |f| %>
      <div class="form-inputs">
        <%= f.input :name, collection: @voted_staffs, label: false   %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, 'REMOVE STAFF FROM POLL', class: "btn btn-info" %>
      </div>
    <% end %>
  <!-- • change the vote from open to closed -->
  <hr>
    <%= link_to "CLOSE POLL", admin_stop_vote_path, class: 'btn btn-info' %>
  <!-- • view the results so far for each member of staff -->
  <hr>
    <%= link_to "VIEW CURRENT RESULTS", votes_path, class: 'btn btn-info' %>
  <!-- • restart a vote by setting the vote for all staff to zero -->
  <hr>
    <%= link_to "RESET POLL", admin_votes_path, class: 'btn btn-info', method: :delete, data: { confirm: "Are you sure you want to delete?" }  %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>
    Nittygritty - Staff of the Month
    <i class="fa fa-hand-o-right" aria-hidden="true"></i>
  </h1>

  <%= simple_form_for(@staff) do |f| %>
    <% if @staff.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @staff.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-inputs">
      <%= f.input :email, placeholder: "Log In With Your Email" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'LOG IN', class: "btn btn-info" %>
    </div>
  <% end %>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-box">
    <div class="footer-logo">
      <%= link_to root_path do %>
        <%= image_tag "favicon.png" %>
      <% end %>
    </div>
    <div class="footer-admin">
      <p><%= link_to "ADMIN?", admin_path, class: "footer-admin-p" %></p>
    </div>
  </div>

  <div class="footer-copyright">
    <p>&copy; 2018 Nittygritty</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <div class="navbar-left">
    <div class="navbar-logo">
      <%= link_to root_path do %>
        <%= image_tag "favicon.png" %>
      <% end %>
    </div>
    <div class="navbar-brand">
      <p>nittygritty</p>
    </div>
  </div>

  <!-- Add a new team -->
    <div class='navbar-add'>
      <%= link_to "SEE RESULTS", votes_path, class: 'navbar-link' %>
    </div>
  </div>
</div>

app/views/staffs/index.html.erb
<div class="container">
  <h1>this is a staff index page</h1>
</div>

app/views/staffs/show.html.erb
<div class="container">
  <h1>Vote Your Favorite Staff</h1>

   <%= simple_form_for [@staff, @vote] do |f| %>
    <div class="form-inputs">
      <%= f.input :voted_staff_id, collection: @voted_staffs  %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'VOTE', class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/voted_staffs/index.html.erb
<div class="container">
  <table>
    <thead>
      <tr>
        <td>Number</td>
        <td>Name</td>
      </tr>
    </thead>
    <tbody>
      <% @voted_staffs.each do |staff| %>
        <tr>
          <td><%= staff.id %></td>
          <td><%= staff.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<%= link_to "ADMIN PAGE", admin_path, class: 'btn btn-info' %>
</div>

app/views/votes/index.html.erb
<div class="container">
  <h1>This is vote result page</h1>

  <p id="notice"><%= notice %></p>

  <% arr = [] %>
  <% array = [] %>
    <% @votes.each do |vote| %>
      <% array << vote.voted_staff.name %>
    <% end %>
  <% arr << array %>
  <% voted_array = arr[0][0..-1].each { |x| print x } %>

  <% counts = Hash.new 0 %>
  <% voted_array.each do |a| %>
    <% counts[a] += 1 %>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      <% counts.each do |k, v| %>
        <tr>
          <td><%= k %></td>
          <td><%= v %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/votes/new.html.erb
<div class="container">
  <h1>new vote page</h1>
</div>